# Generated by Django 6.1.1 on 2026-09-18 13:50

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone number')),
                ('goals', models.JSONField(blank=True, default=list, verbose_name='what brings them')),
                ('goals_other', models.CharField(blank=True, max_length=200, verbose_name='other reason')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='experiences they want')),
                ('interests_other', models.CharField(blank=True, max_length=200, verbose_name='other experience')),
                ('source', models.CharField(blank=True, choices=[('social', 'Social Media'), ('friend', 'Friend/Family'), ('search', 'Online Search'), ('ads', 'Ads'), ('other', 'Other')], max_length=20, verbose_name='where they heard about us')),
                ('wants_updates', models.BooleanField(default=False, verbose_name='wants updates')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='language')),
                ('referral_code', models.CharField(default=home.models.new_referral_code, editable=False, max_length=12, unique=True, verbose_name='referral code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='joined')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='home.waitlistsignup', verbose_name='referred by')),
            ],
            options={
                'verbose_name': 'waitlist signup',
                'verbose_name_plural': 'waitlist signups',
                'ordering': ('-created_at',),
            },
        ),
    ]
